### ISSUE TITLE
[FR] GMail-ish UI approach

### ISSUE THREAD

**Issue by ildar** [FredJul/Flym#12]
Google spends a lot of money for UI development. And many people find GMail UI useful.
So I suggest to borrow some things from the UX.

1. https://github.com/HoloAddict/FeedEx/issues/1 already started this
2. New FR: have two-pane interface for landscape: left pane with items list, right is the current item contents.

This is just a suggestion, what do you think about it?

**Comment by FredJul** [comment]
I think we are not very close to the gmail ui, so I'm closing this issue
