### ISSUE TITLE
[query] How can I access full error message for feed?

### ISSUE THREAD

**Issue by kwill** [FredJul/Flym#156]
In a previous issues (#155) I encountered an error with a feed. The only place I could see the error message was in the feed margin if I made read posts visible, and even then it was truncated to what could fit in the margin "Error: length=20; regionSt..." and another "Error: Unable to resolve h..." (I'm guessing that's "host" ;)

How can I access full error messages?

**Comment by ildar** [comment]
Please reopen, I stumbled on this one again.

**Comment by ildar** [comment]
I got endless update. How can I debug it / find the lasting feed?
