### ISSUE TITLE
[feature request] Global setting to "Retrieve the full text"

### ISSUE THREAD

**Issue by kwill** [FredJul/Flym#157]
After importing a number of feeds via OPML I discovered the "Retrieve the full text" checkbox when editing one of them. Currently I would have to go through and tick this for every feed. Is it possible to make a global default for this? (Or does this exist and I've missed it?)

**Comment by wp9015362** [comment]
@FredJul :

I would second this request.

Please add an option to always preload/retrieve the full text.

But, again, please make it optional.

It would be much appreciated.

Regards
