### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by ritzmann** [FredJul/Flym#160]
The one missing feature that prevents me from switching entirely to FeedEx yet is basic auth. It would be great if I could simply enter a username and password in the settings of each feed.

**Comment by tasmo** [comment]
Is it working now?

**Comment by promovicz** [comment]
I would also like to use Flym with some closed feeds.
My use-case is viewing the changelogs of Wikis on the go.

**Comment by digikar99** [comment]
Any update on this?
