### ISSUE TITLE
more intuitive back button behaviour

### ISSUE THREAD

**Issue by chriscamacho** [FredJul/Flym#166]
I can't figure out pull requests who ever invented git was taking the preverbial...

I find it more convienient if the back button opens the side bar then on second press quits
this code will implement such behaviour - you may wish to implement it as a preferences setting

```
@Override
public void finish() {
    if (mCanQuit) {
        super.finish();
        return;
    }

    //Toast.makeText(this, R.string.back_again_to_quit, Toast.LENGTH_SHORT).show();

    mDrawerLayout.postDelayed(new Runnable() {
        @Override
        public void run() {
            mDrawerLayout.openDrawer(mDrawerList);
        }
    }, 50);


    mCanQuit = true;
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            mCanQuit = false;
        }
    }, 3000);
}
```

**Comment by bquistorff** [comment]
Was there a reason for closing this? I agree with the poster that it might make more sense to have back open the side bar first. This is the behavior in some other apps.
