### ISSUE TITLE
background color on pages which are not  rendered yet

### ISSUE THREAD

**Issue by jotwewe** [FredJul/Flym#199]
When swiping from one entry to the next a white page appears until it gets replaced by the entry itself. 
Using the dark theme in the dark this bright white page is blinding one's eyes.

**Comment by FredJul** [comment]
Funny, I daily use the dark theme and I've never saw that. Can you reproduce with the last version? Which android version/phone do you have?

**Comment by jotwewe** [comment]
It's an samsung galaxy s4 mini, android 4.2.2. I'm using flym 1.8.0
installed via f-droid.

On this device I disabled automatic screen brightness because it
is too bright usually and especially when reading in the dark the
lowest setting is too bright, too -- which is why I'm additionally
using a tool called "Dimmer" (also on f-droid). Without this dimming,
unread entries and entry details are blinding my eyes.

...under this circumstances the grey on black "read" setting does not
provide enough contrast to be readable. I remember having other
situations (day light indoors or outdoors) in which I felt every app was
perfectly readable (bright enough), but flym's "read" entries had just
been too dark.

Furthermore I don't think the difference between read and unread must
be high -- in case I don't want to see unread items, I hide them
anyway. For me it would even be fine to have read and unread entries
display in the same colour.
