### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [FredJul/Flym#202]

**Comment by repsorp** [comment]
Option to disable letter icons please !

**Comment by repsorp** [comment]
Option to disable letter icons please.
In the meantime I had to switch back to ownCloud News Reader...

**Comment by ildar** [comment]
Why don't you just stick with an older version that doesn't have these
icons? AFAIK you can disable updating in both Play Market and f-droid.
Just to avoid spamming here...

**Comment by svetlemodry** [comment]
Looks to me like a feature request than as a spam.
+1 from me for an option to disable the icons - I liked the old look better.

**Comment by repsorp** [comment]
Is it spamming to relate excessive data consumption ?

**Comment by ildar** [comment]
Is it spamming to repeat
> Option to disable letter icons please !
again and again?

**Comment by gplaystored** [comment]
Good day,
Flym's catch words are "light" and "modern". Most people do not have the money to purchase more data and therefore, the ability to customize is important. An option in settings to accomadate those who cannot afford more data charges, would be appreciated. (modern and most importantly "light" esp. on the pocket.)

**Comment by FredJul** [comment]
I'm closing this issue since there is other ticket for the same thing: an option for disabling the letter.
