### ISSUE TITLE
no (more) fulltext download

### ISSUE THREAD

**Issue by homofaber-o** [FredJul/Flym#209]
i use the last flym package from the fdroid 'shop' 
on a first setup, all feed download news in fulltext. after a new 'setup' from my android (4.2) tablet  i copy the flym backup (opml) file to android. flym find his backup - all feeds are back. but, some feeds i get no (more) fulltext. 

a second issue is: if i will setup a new feed - i go to the settings give url, a name and the check for fulltext download. but, i dont have a 'chancel'or 'OK' button more. to save my new feed?! 

i am new on github, if you know how i can bring up a screenshot, pls give me a tipp ....

thanks for flyn. i <3 rss .... and miss aaron

**Comment by FredJul** [comment]
should be good with 1.8.0, thanks for the report
