### ISSUE TITLE
Cancel "mark all as read"

### ISSUE THREAD

**Issue by Dostoi** [FredJul/Flym#210]
It would be nice to be able to cancel marking as read every article if you've done it by mistake. Maybe by changing the button fonction when there is no article left, to mark as unread the last read article ?

**Comment by JozefJarosciak** [comment]
In my opinion all this needs is a prompt asking if user really wants to mark every single article as read.
It's very common to make this mistake.

**Comment by Dostoi** [comment]
Yes or something like that could be nice too

**Comment by CodingSpiderFox** [comment]
Yes, I think so, too @Dostoi 

@FredJul: Please tell us why you closed the issue

**Comment by ildar** [comment]
Fred wrote issues were mass closed because of the complete rewrite in v2.
We just need this one reopened if persists in v2

**Comment by ilf** [comment]
A confirmation prompt would be awesome.

Even further, I would also like to completely disable and hide this button, see https://github.com/FredJul/Flym/issues/412
