### ISSUE TITLE
F-droid has wrong source code link.

### ISSUE THREAD

**Issue by Techwolf** [FredJul/Flym#211]
When using fdroid, there is a menu item "source" that will open up the source code url using the associated app, the browser or an app like github. Github will error out, hence this report.

**Comment by daggerstab** [comment]
I don't know if the F-Droid package is prepared by the developer or someone else. You can try the F-Droid repository data tracker: https://gitlab.com/fdroid/fdroiddata/issues

**Comment by krt16s** [comment]
I updated the URLs, also the redirects work fine... so this is most likely an issue with the associated app.
