### ISSUE TITLE
Error:(21) A problem occurred evaluating project ':app'. > Could not find property 'KEYSTORE_PATH' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

### ISSUE THREAD

**Issue by timot7782** [FredJul/Flym#213]
Hi, how to solve this problem?

**Comment by emolinare** [comment]
I am running into the very same issue:
![image](https://cloud.githubusercontent.com/assets/3492464/6062499/4e02c8d0-ad1e-11e4-9b3f-ebf75ffc7218.png)

**Comment by lovellfelix** [comment]
https://github.com/FredJul/Flym/blob/master/app/build.gradle#L19

signingConfigs {
        release {
            storeFile file(KEYSTORE_PATH)
            storePassword KEYSTORE_PASSWORD
            keyAlias KEY_ALIAS
            keyPassword KEY_PASSWORD
        }

You can either comment out those lines or replace it with your Key store variables. 

See this doc for more information about generating your keystore

**Comment by timot7782** [comment]
Hey,

I commented out those lines and now i m getting this error:
Error:FAILURE: Build failed with an exception.

* What went wrong:
Task '' not found in root project 'Flym'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace
option to get the stack trace. Run with --info or --debug option to get
more log output.

**Comment by emolinare** [comment]
I've commented it this way:

signingConfigs {
release {
// storeFile file(KEYSTORE_PATH)
// storePassword KEYSTORE_PASSWORD
// keyAlias KEY_ALIAS
// keyPassword KEY_PASSWORD
}

and it worked for me.

**Comment by timot7782** [comment]
yeah still having the same error:
Error:FAILURE: Build failed with an exception.

* What went wrong:
Task '' not found in root project 'Flym'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace
option to get the stack trace. Run with --info or --debug option to get
more log output.

**Comment by lovellfelix** [comment]
@timot7782 There is a good chance you removed a curly bracket that you shouldn't. Try cloning a new copy of flym or git checkout app/build.gradle (which ever you're comfortable with) and comment out the signing variables as @emolinare mentioned.

**Comment by FredJul** [comment]
should be fixed now
