### ISSUE TITLE
Use Code

### ISSUE THREAD

**Issue by DVYAGROUP** [FredJul/Flym#227]
We have to make a RSS Reader App So may we use your Code for this.
Is there any problem related to Copyright for Using Your Code..

**Comment by suyash1629** [comment]
Read the license file included in the source code. And you can't close source the app you are making based on this application. This is one of the condition included in the license of this app:

"For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights."

**Comment by DVYAGROUP** [comment]
Thanks..

**Comment by FredJul** [comment]
Thank you suyash for this exact description.

I'm closing this ticket now since it's not an issue at all.
