### ISSUE TITLE
Please remove proprietary non-native scrollbar in "Entries" and "Starred" view

### ISSUE THREAD

**Issue by wp9015362** [FredJul/Flym#254]
Hello,

in the "Entries" and in the "Starred" view, there is a scrollbar at the right side.

This scrollbar seems to be non-native, i.e. it seems to be a scrollbar which is proprietary to Flym.

I have not seen such a scrollbar in any other app.

The issue is:

I often scroll through the "Entries" and "Starred" view by swiping through it and then suddenly (accidently) hit the scrollbar at a certain position and it makes the view jump to that position.

That's really annoying and not helpful.

So, could you please remove that proprietary non-native scrollbar?

It would be much appreciated.

Regards

**Comment by suyash1629** [comment]
The scrollbar is not proprietary. its the native scrollbar that is included since the introduction of android 5.0.

**Comment by wp9015362** [comment]
When it has been introduced with 5.0 Lollipop, then why do I see it in Flym on 4.4 KitKat?

**Comment by suyash1629** [comment]
The navigation hamburger was also introduced in 5.0 so why do you see it in KitKat or even jellybean and ICS? the scrollbar is also the same thing..

**Comment by suyash1629** [comment]
The navigation hamburger was also introduced in 5.0 so why do you see it in KitKat or even jellybean and ICS? the scrollbar is also the same thing..
