### ISSUE TITLE
Header for text selection has same color as buttons on it. 

### ISSUE THREAD

**Issue by 27himanshu** [FredJul/Flym#268]
Take a look at the [screenshot](http://i.imgur.com/UIhDTV6.jpg)

**Comment by vixsomnis** [comment]
I was going to comment that I haven't seen this issue, but I have it also (on 1.8.1).
![screenshot_2015-04-14-01-08-02](https://cloud.githubusercontent.com/assets/8848970/7130731/57093388-e243-11e4-8b64-862960442053.png)

**Comment by suyash1629** [comment]
Which android version are you using?? I don't find this issue on lollipop..

**Comment by 27himanshu** [comment]
Android 4.4.4 Moto X
Also, I'm using dark theme

**Comment by vixsomnis** [comment]
4.4.2, LG G2 VS980. It is a custom ROM, though.

**Comment by vixsomnis** [comment]
The buttons are visible in light mode, but not dark mode.
