### ISSUE TITLE
Missing gestures

### ISSUE THREAD

**Issue by Cotopaxi42** [FredJul/Flym#332]
Hi,
First, thanks for updating Flym again. 
Could you add something that I like a lot in the old Flym: the gestures (left swipe to remove, right to add to favourites)?
And maybe the date of the article next to the name in the entries list (like the old Flym as well)?
Thanks!

**Comment by infinitytec** [comment]
I would like swipe to mark as read.
+1 on the date information.

**Comment by FredJul** [comment]
that was actually in my plans, and it will be soon delivered
