### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by afmbsr** [FredJul/Flym#334]
Hi, 

There are some suggestions. It's great to add them to flym

- Add zoom feature via two-finger spacing. Because some details in the pictures need not appear clearly

- Show feed link and logo while searching to add new feeds. Because sometimes show more than one feed with the same name

- Add an option to turn off notifications

Thank's

**Comment by infinity85** [comment]
Thank you @FredJul  that you already implemented the swipe down to view full text feature! You are the best :)

**Comment by FredJul** [comment]
well, that was a good idea and actually quite quick to do :)
