### ISSUE TITLE
Swipe to dismiss in list?

### ISSUE THREAD

**Issue by rogalian** [FredJul/Flym#335]
I've just switched from the open source Feeder to Flym as Flym actually works with all my feeds and generally functions more neatly.

I miss being able to rapidly flick headlines out of the list without needing to read them.

**Comment by FredJul** [comment]
Since yesterday you can do it on the "unread" tab, I believe it is what you describe here.

**Comment by rogalian** [comment]
Brilliant :) I see F-Droid is behind the Play Store for versions, so I'll wait for it to hit the safe store. Can see some other fixes I've already worked around too (manually transcribing an OPML).

Many thanks.
