### ISSUE TITLE
Refresh feeds only on open

### ISSUE THREAD

**Issue by nautilusx** [FredJul/Flym#338]
Hi,

thank you for your great app. 

Please add the option to refresh all feeds after opening the app.

**Comment by afmbsr** [comment]
Select All entries and swipe to down :)

**Comment by FredJul** [comment]
actually that's what happen... there is no option but it will refresh everything at the app's opening. Do you mean it's not working or you need an option to disable it ?

**Comment by nautilusx** [comment]
@afmbsr: I know that you can swipe down to update.

@FredJul:
In the previous version there was this further possibility under the settings.

I have deactivated the automatic update and I only want to update all feeds when I open the app.
Maybe you can reuse the old code.

This feature is especially important for all people who do not want to seem addicted to their smartphone. Another important point is the option to deactivate notifications.

**Comment by FredJul** [comment]
@nautilusx I'm sorry but I still don't get it: if you want to deactivate the automatic synchronisation there is a setting for that, so you won't receive any notification while not using the app.

There is no setting to deactivate the refresh at the app opening, but from what I read you don't really care about that

**Comment by nautilusx** [comment]
@FredJul I mean this option. You will see it on the screenshot of the old version 1.9x.
![screenshot_flym_1 9](https://user-images.githubusercontent.com/8766955/42475350-ab6a3fa4-83ca-11e8-8876-0f1bd0f074ea.png)

The new version 2.06/2.07 doesn't refresh by opening the app when I deactivate the automatic synchronisation.

By the way Flym is the best rss feed app! Thank you!

**Comment by FredJul** [comment]
Now I understand your problem, thanks.

Today you can already almost have what you want: let the autosync enabled and set the refresh interval to the max value. You will now rarely have a notification but it will still refresh on open.

I'll think about improving that, but on the other side I like when the number of options is as small as possible.

**Comment by infinitytec** [comment]
I would appreciate that as well.

**Comment by nautilusx** [comment]
@ildar I changed the title. My issue is different - I want an automatic refresh but not with a static refreshing interval only when you open that app.
