### ISSUE TITLE
Option to disable left/right swipe in article

### ISSUE THREAD

**Issue by AeliusSaionji** [FredJul/Flym#341]
This is my first Android phone in a while, and I've noticed that Android has really tight (bad) tolerances for tap+gesture input.

While reading an article, frequently I try to scroll down and instead get locked into left-right motion.

Since I am picky about what I read, I don't imagine myself ever using this to get to another article. The option to disable it would just neatly eliminate accidents.

Thanks again!

**Comment by momoe** [comment]
I woul like to see the swipe gestures remain but have much quicker action time to move in to the next article

**Comment by FredJul** [comment]
that's another issue and I tend to agree with you, but that's not my top priority right now
