### ISSUE TITLE
Bug in the new update 2.0.8

### ISSUE THREAD

**Issue by afmbsr** [FredJul/Flym#345]
There is an increase at the beginning of any link when a new feed is added by keyword. This disables feeds

This increase (feed/)

**Comment by FredJul** [comment]
I'm sorry but I didn't understand, could you please provide more info and a screenshot please?

**Comment by afmbsr** [comment]
Adding a new feed by keyword results in a bug in the link
![screenshot_2018-07-11-14-16-46](https://user-images.githubusercontent.com/38974362/42568933-7845fc96-8517-11e8-939c-4887cb947b13.png)
![screenshot_2018-07-11-14-17-49](https://user-images.githubusercontent.com/38974362/42568962-98d70536-8517-11e8-839a-c604dfdddb9b.png)

**Comment by FredJul** [comment]
Oh... you're right.... that a very stupid mistake from me.

It's fixed now, I'll publish a new version very soon
