### ISSUE TITLE
Allow users to sort entries by age 

### ISSUE THREAD

**Issue by ghost** [FredJul/Flym#347]
Hi, right now, entries are only sorted by newest first. I'd like to sort them by oldest first so that the oldest entry is at the top of the list and I get newer ones as I scroll down. 

May we please have this feature? Thanks.

**Comment by Jazcafe** [comment]
I would also like to sort by oldest first.

Thanks.

**Comment by mitsnosrap** [comment]
@FredJul I think this can be closed as the latest version supports sorting by oldest.
