### ISSUE TITLE
Option for light theme

### ISSUE THREAD

**Issue by momoe** [FredJul/Flym#350]
Having a white background theme would be more preferable, so please include a light theme option. Or better yet have a three colors picking option. Color 1, background color, Color 2, accent/banner app color, Color 3 text color. (Links can also be Color 2, for a more unified look)

This would give users the ability to match themes with their phones while promoting this as a better RSS than the others.

**Comment by kuba-orlik** [comment]
I agree, lack of light theme is the reason I'm still on spaRSS

**Comment by Jazcafe** [comment]
Yes please, a light theme and an option to choose the link colour.

**Comment by FredJul** [comment]
lavendthomas implemented a first light theme option, which I agree to merged ;) So I'm closing the ticket.

However this doesn't mean there is nothing to improve. Please open some other tickets if you feel a need for that.
