### ISSUE TITLE
Import/Export feed library

### ISSUE THREAD

**Issue by momoe** [FredJul/Flym#352]
Would be very useful to import desktop OPML files which contain the entire RSS collection into Flym instead of manually input many, many RSS feed by hand.

**Comment by gkaklas** [comment]
I haven't tested them but there are options to import from and export to OPML at the top right of the sidebar (3-dot menu).

**Comment by momoe** [comment]
I didn't see this, my apologies. I'll give it a test and report back any bugs.

**Comment by FredJul** [comment]
I close this issue for now, please open a new one if you have import/export problems
