### ISSUE TITLE
Feature: Flym Link/Button for a Web Site

### ISSUE THREAD

**Issue by ilyaigpetrov** [FredJul/Flym#353]
I want to add a link to a website which should be opened in a RSS Reader on Android (in Flym).
I know little about it, but I guess there should be a special domain, e.g. flym.org, and Flym app should register itself as a handler of links of this domain. Then we could add links like `https://flym.com/rss-url=...` to our websites. If such links are opened on PC then they should redirect somewhere. If Flym is not installed they should redirect somewhere. It will be good if upon tapping an rss-link a variety of all RSS readers installed would be offered to open the link.

**Comment by FredJul** [comment]
It is technically possible to register a domain for flym and open the app on a flym.com link. But I honestly don't think it will be really used and moreover this will cost me a bit, so I don't plan to do that.

**Comment by ilyaigpetrov** [comment]
I guess you may use GitHub Pages subdomain, so there will be no expense on a domain, all redirects may be done in JavaScript. Poor man solution. But if you don't think the feature is coveted, then let it be.
