### ISSUE TITLE
Feature request: Filter out duplicated entries across multiple feeds

### ISSUE THREAD

**Issue by CodingSpiderFox** [FredJul/Flym#360]
Some news portals, like heise.de post the same article to multiple feeds.
However, I want to follow all the feeds in order to not miss anything.

But I don't want to spend time deleting duplicated entries.

So when an item is processed an another item is already in another feed, having the same title, the new item should not be added to the feed view

**Comment by CodingSpiderFox** [comment]
@FredJul: Could you please outline the steps I need to take in order to implement this? Then, I'd be happy to start working on this and make a pull request

**Comment by FredJul** [comment]
Hum I didn't really have the case and didn't thought about that...

I guess an easy way would be to change the id generation in Entry.kt to something like:
`item.id = (link ?: uri ?: title ?: UUID.randomUUID().toString())).sha1()`

Should work but would need to be tested

**Comment by FredJul** [comment]
Oh, and I forgot: thanks a lot for your proposal! Always nice to see people invested in a project you have created. I still have plenty to do on that app, any help is welcome

**Comment by FredJul** [comment]
Well actually one problem of that solution would be that all existing entries will be duplicated at first refresh... So either we would need to do a DB migration of previous ids, either find another solution.

For instance we could also make the link field unique, but then again we would have a DB migration to do.

**Comment by CodingSpiderFox** [comment]
Why not make a select by title from the database before inserting a new item? If the title is already present, don't do an insert. 

Could we maybe have a little programming session soon? I'm not that familiar with Kotlin

**Comment by FredJul** [comment]
Doing a title request before inserting the entry would be approximately the same as putting the title column unique, but in much less efficient way so it's better to use the unique keyword. Also I believe it's better to do this on the link field, the title could be similar between several different entries.

And concerning the programming session I'm currently in holidays and don't have much free time these days, but I guess it wouldn't harm to describe a bit more the architecture and used libraries in the readme, I'll try to do this in a near future

**Comment by CodingSpiderFox** [comment]
Thanks for the hints! The reason to do a database request was that I wanted to avoid changing the existing table because I wasn't sure about the database migration.

**Comment by FredJul** [comment]
True, I admit it makes it a bit simpler and will certainly work, but I still believe the UNIQUE solution is a better way. I believe the DB migration to be quite simple : in the addMigrations methods we would need to add an ALTER TABLE query to add the unique constraints with an ON CONFLICT IGNORE rule.

But this would need some testings to be sure I'm saying anything stupid ;)

**Comment by FredJul** [comment]
closed since PR actually merged
