### ISSUE TITLE
Sharing buttons for bookmarked disapear

### ISSUE THREAD

**Issue by mouarfff** [FredJul/Flym#363]
I use flym since years and I need to make press revue  and I used sharing mail button for my bookmark to transfert it on my computer but i can't see this in the last version !

I'ts very difficult now and i dicrease productivity and make very long time to copy links on mail (over 40 to 60 bookmarks to read analyse and comment is impossible without this sharing mode)...

**Comment by FredJul** [comment]
That clearly something I simply forgot. I quickly fixed it (and it will soon be delivered) but the technical solution is not perfect, I'll need to rework that later so I keep that issue open

**Comment by mouarfff** [comment]
Ok think's !

But there is another bug, when I'm in all items, and i go to "sharing" button, the app crashes :(

**Comment by FredJul** [comment]
I just did a workaround about that (limiting the text to 300000 characters). Nothing perfect but I'm actually not sure how to fix that without this ugly workaround.

Let me know if this works in your case, otherwise please reopen the ticket.
