### ISSUE TITLE
Can't rename Groups

### ISSUE THREAD

**Issue by Quantum1337** [FredJul/Flym#365]
Hey,

at first thank you for this great app!

I have a problem  renaming Groups. Steps to reproduce:

1) Add a new Group
2) Rename it, by long tapping the Group and tapping  "Edit Feed". The Group-Name is listed under " Feed-Name"
3) Press OK. Nothing will happen.

Thank you for looking on to this.

**Comment by afmbsr** [comment]
You are right

There is a temporary solution :

Extract the feeds from within the group folder and then delete the empty folder and finally create a new group with the name you want

**Comment by FredJul** [comment]
thanks for reporting it, that is now fixed and will soon be delivered
