### ISSUE TITLE
Force close when clicking article for all entries

### ISSUE THREAD

**Issue by bart3005** [FredJul/Flym#366]
I have my subscriptions in folders. When I go to an article form the all entries I get a force close. When I go to the article from the actual folder it works fine.

This is on version 2.

**Comment by GitteHuber** [comment]
Same issue here, app version: **Flym 2.0.9** (F-Droid)

**Steps to reproduce:**
1. Add some feeds to Flym an sync them
2. Switch from a feed specific directory to the "Alle entries" directory
3. Try to open any synced news/article in "Alle entries"
4. Flym crashes

**Logcat:** [flym_crash_all_entries.txt](https://github.com/FredJul/Flym/files/2299421/flym_crash_all_entries.txt)

**Comment by FredJul** [comment]
I did a fix to avoid that and will soon publish it, please tell me if that is working for you
