### ISSUE TITLE
Problem with ordering of groups

### ISSUE THREAD

**Issue by Quantum1337** [FredJul/Flym#369]
Hello,

i encountered a problem, when i try to order my groups. Steps to reproduce:

1) Have a lot of groups, i have 8
2) Go to the "reorder“ menu
3) Try to move the last one to the middle. It will shown up as the first entry. When you move the last one to the second last one it works. When you try to move the first,second,third,fourth?! one, nothing will happen.
4) I listed only a few situations, please have a own look on to that behavior.

Thank you, for having a look on to this

**Comment by FredJul** [comment]
I believe it has been fixed. Please reopen if not.
