### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by stef204** [FredJul/Flym#370]
@FredJul Hi Frederic, thanks for this app.
When one views a item inside the app, I imagine it uses "Webview"?

What is the treatment of cookies?  Are they accepted and stored by default?
If so, would you be open to adding a simple feature to manage these, i.e. mostly delete them by feed or in general (all)?

**Comment by stef204** [comment]
I looked at source code and I see line 138 in /Flym/app/src/main/java/net/frju/flym/service/FetcherService.kt

    _MANAGER.cookieStore.removeAll() // Cookies are important for some sites, but we clean them each times

This seems to mean Flym accepts all cookies but deletes them each time.  Not sure what "each time" actually means, if you can clarify at some point.

Thanks.

**Comment by Echolon** [comment]
@FredJul do you have an answer to this?

**Comment by FredJul** [comment]
As the comment says : cookies are enabled because it is sometimes mandatory, but they are cleaned before the refresh process (ie. cleaned once before refreshing all feeds)

I personally believe it is good enough and that it does not need any option

**Comment by Echolon** [comment]
Thanks!
