### ISSUE TITLE
Using data instead of wifi to load articles

### ISSUE THREAD

**Issue by neet0** [FredJul/Flym#372]
I don't have problems loading articles at home, but when I try to use 4G while I'm on the go, it only gives me the links of the articles instead. I was wondering if this was a bug or not a feature yet.

**Comment by FredJul** [comment]
quite strange, I see no reason... seems to work on my phone. Can you give me an example feed link?

**Comment by neet0** [comment]
Looks like it just needs some time to load. It wouldn't work the first day I tried the app, but now it does.
