### ISSUE TITLE
Articles reappear after marking them as read

### ISSUE THREAD

**Issue by schulle4u** [FredJul/Flym#375]
Since V2.1.1 some articles annoyingly reappear over and over after marking them as read. Even marking them as favorite doesn't help, they are being removed and reappear in the unread tab immediately upon next check. This doesn't happen with all feeds, an example can be found here: 

`https://robbinaer.info/feed.php?rss`

Using a Moto G4 Plus running Android 7.0 and the F-Droid build of Flym. 

Steffen

**Comment by FredJul** [comment]
I added this feed and try to refresh it several time, the one and only entry I see is not going back to the unread list.

I'll continue to test it, but for now I don't know what can cause that issue

**Comment by schulle4u** [comment]
I'll describe the exact szenario to reproduce the behaviour: 

1. Add my example feed along with some other frequently updated feeds and mark the articles as read.
2. Close Flym and wait for the next automated article fetch, currently set to 1 hour in my case.
3. Open Flym and read the newly added articles, if any.
4. After marking all articles as read, the previously read article from my example feed suddenly reappears in the unread list. 

This procedure repeats as soon as I mark the article as read. After next automated fetch the article again shows up in the list. Another reader of my blog confirms this behaviour when using Flym, this also happens with some other feeds. I'll post another article this evening or tomorrow and see what happens then. 

HTH
Steffen

**Comment by Echolon** [comment]
I will close this as duplicate. Please vote and comment in the referenced issue.
