### ISSUE TITLE
Stop refreshing at the app opening

### ISSUE THREAD

**Issue by ildar** [FredJul/Flym#381]
Frédéric Julian in https://github.com/FredJul/Flym/issues/338:
> There is no setting to deactivate the refresh at the app opening

That's really disappointing. The app appears to be uncontrollable when simple opening the app starts network leech processes.
Please make the option, preferably opt-in as in v1

**Comment by ildar** [comment]
BTW "Full text" button is disfunctional during refresh. Then UX is negative indeed.

**Comment by nautilusx** [comment]
@ildar There is an easy way for you. If you want no automatic refresh just disable the first options under settings "enable automatic refresh". After you disabled this option you have no automatic refresh.

For manual refresh - just swipe down.

(my issue is different - I want an automatic refresh but not with a static refreshing interval only when you open that app)

**Comment by ildar** [comment]
I want completely opposite: (a) no refresh on app open but (b) regular
refresh once a day.

**Comment by ilf** [comment]
I agree, I would like a periodic refresh, but no refresh when opening the app.
