### ISSUE TITLE
[Feature Request] Pure black theme

### ISSUE THREAD

**Issue by prg318** [FredJul/Flym#397]
It's great that Flym has an option for "Enable dark theme", but it would be great for AMOLED display users to have a pure black background option for the dark theme

**Comment by lavendthomas** [comment]
I started working on it today. There is still lots of issues for now so I haven't made a pull request yet.

Could you give me feedback so I can improve it before submitting it to Frédéric Julian? 
For information you can choose between the light, dark(defaut) and black theme in the settings.

![screenshot_1538074855](https://user-images.githubusercontent.com/30930211/46168627-4d738000-c299-11e8-85fa-7942ee169722.png)
![screenshot_1538074757](https://user-images.githubusercontent.com/30930211/46168697-83186900-c299-11e8-9b45-166780d9ed74.png)

**Comment by FredJul** [comment]
I personally like it ;)

**Comment by prg318** [comment]
This is exactly what I had in mind :)  Hope something like this gets merged :D

**Comment by FredJul** [comment]
thanks to lavendthomas, this can now be closed ;)
