### ISSUE TITLE
Single quote issue with some sources: shown as &#039;

### ISSUE THREAD

**Issue by misha-franz** [FredJul/Flym#399]
![screenshot_20180927-152536](https://user-images.githubusercontent.com/6687525/46178098-47b27600-c26a-11e8-9ebd-44670aa0defa.png)

Daily Wire is one of the examples. Note not all single quotes are shown incorrectly, but most for this source are.

**Comment by FredJul** [comment]
fixed and a new version will soon be published
Thanks for the report and sorry for the delay
