### ISSUE TITLE
Retrieving full text is slow

### ISSUE THREAD

**Issue by phavx** [FredJul/Flym#40]
I'm glad you've got the "fetch full text"-feature, but it's terribly slow. I added the feed of spiegel.de, set it to fetch full and it took >2 mins on WLAN, while a quickly done and not in any way optimized ruby script took <20s for the same task.

I'm guessing you're processing item after item and not in parallel? I hope that gets optimized, since I'm planning to add quite a few feeds of which I'd like to have the full text and in the current state, that would take ages and suck the battery dry.

**Comment by maninthemiddle01** [comment]
I really like the look and feel of your app and it would be nice to see if the full text shows faster. spaRSS does this the way I like, maybe it uses another method (sry, I am not a programmer, so I cannot tell more precise).
