### ISSUE TITLE
Crash when y tape "sharing" button

### ISSUE THREAD

**Issue by mouarfff** [FredJul/Flym#402]
Hello,

When i go to "tout les articles" (all entries ?) and I go to the sharing button, the application always crashes

I'm on a homtom ht70 and i use f-droid and the last version of flym (upgraded today for me)

**Comment by FredJul** [comment]
I just did a workaround about that (limiting the text to 300000 characters). Nothing perfect but I'm actually not sure how to fix that without this ugly workaround.

Let me know if this works in your case, otherwise please reopen the ticket.
