### ISSUE TITLE
option to disable button "mark all as read"

### ISSUE THREAD

**Issue by ilf** [FredJul/Flym#412]
I never use the "mark all as read" button, but it's so prominent that I accidentialy click it from time-to-time. I would love to disable it completely.

spaRSS did that at https://github.com/Etuldan/spaRSS/commit/af80e3f8d1b47f68a065bb524de40e48711bb6d9

Thanks, and keep up the good work!

**Comment by int-ua** [comment]
It can be accidentally clicked especially easy because button to cancel archiving appears almost exactly where it's placed and just for a couple of seconds.

**Comment by ildar** [comment]
then should be reopened.

**Comment by heimpogo** [comment]
Please add this option. I have lost my unread list multiple times this way.
