### ISSUE TITLE
option to disable notifications

### ISSUE THREAD

**Issue by ilf** [FredJul/Flym#413]
I would like to disable notifications. Currently, I see no option to do this. (A workaround would be to do it on the Android level, but I'd rather not generate them in the first place.)

spaRSS has an option for this: https://github.com/Etuldan/spaRSS/blob/master/mobile/src/main/res/xml/general_preferences.xml#L168

Thanks!

**Comment by mitsnosrap** [comment]
@FredJul I believe this can be closed as this option now exists.

**Comment by FredJul** [comment]
you're totally right! thanks
