### ISSUE TITLE
Configure What Time of Day for Auto Update?

### ISSUE THREAD

**Issue by glimmerwell** [FredJul/Flym#428]
Is there a way to configure the actual time of day that Flym automatically updates the database? I can't seem to figure it out. If not, can this be added?

Thanks for the awesome software!

**Comment by femirk** [comment]
@glimmerwell 
I can import android studio project but I have a bug that I get constantly.
Have you encountered such an error?

> error: Cannot find getter for field.     private long id;                  
> error: Cannot find getter for field.     private java.lang.String imageLink;

**Comment by Echolon** [comment]
I dont see the general advantage for users

**Comment by FredJul** [comment]
Same for me, I understand it could solve some specific use cases, but I'd rather prefer not having this option since the vast majority of user will almost don't care about it. Moreover, with Android API, there is way to be absolutely certain the refresh will be made at a precise hour.

**Comment by ildar** [comment]
+ there are ways to restrict traffic for particular apps in particular
hours or WiFi versus Mobile internet etc..

**Comment by ildar** [comment]
BTW is there an intent to kick for updates? then automation apps could
start updates when user wants.
