### ISSUE TITLE
Set default RSS more than one

### ISSUE THREAD

**Issue by aminalzanki** [FredJul/Flym#44]
Hi,

I just want to know whether I can simple add several more feeds in .opml file? How to add more default feeds?

Quick reply would be highly appreciated.

**Comment by FL3R** [comment]
Hi, I too would have the same request.  It is an app of an Italian public university pole, which shows the feeds of the educational center, the university and the company for the right to study.  The app would have advertising (a banner below) and the source code would also be published, of course.  can you help me?

**Comment by ildar** [comment]
Let me sound my 5 cents.
I think the two practical approaches possible here:
1. Add some geo-tied suggestions to the app so many such options available
for different places on the Earth. Example: local chats in Telegram.
2. Just put special link where appropriate: on a site, other apps if used.
URL to be chosen from those that Flym supports.

Surely second approach is a lot easier to implement and less intrusive.

>
