### ISSUE TITLE
Share URLs of unread items

### ISSUE THREAD

**Issue by CodingSpiderFox** [FredJul/Flym#451]
I want to have an option to share all URLs as list like I can share a single item via Messengers, Email, etc.

Use case: I want to factory reset my phone but still have ~ 550 items to go through... I want to do that later

**Comment by ildar** [comment]
use backup for that.

**Comment by CodingSpiderFox** [comment]
will try it when I have time

**Comment by Echolon** [comment]
I will close this as you have the export function to my understanding.
