### ISSUE TITLE
Entering URL for a feed? 

### ISSUE THREAD

**Issue by caresrg** [FredJul/Flym#468]
Is there a way to enter a url to subscribe to a feed? When I try "searching" using a url, it just isn't finding the feed.

**Comment by FredJul** [comment]
Well, normally you can enter an URL into the search field. Could you provide me the link itself so I can test it?

**Comment by keunes** [comment]
One example of this I just experienced was http://opensource.com

**Comment by b16r05** [comment]
That website has a dedicated RSS feed/icon: https://opensource.com/feed

**Comment by b16r05** [comment]
and, it just pulled 10 entries today : )

**Comment by keunes** [comment]
Hi @b16r05,
I know they have the direct feed available, and I'm happily receiving their content using the direct feed URL. Maybe I misunderstood, but I thought the OP's comment was providing just the domain should offer the feed of the website(?)

**Comment by b16r05** [comment]
Yes, my mistake... opensource website was just an example. For being able to use URL, take a look at this: https://github.com/yanus171/Handy-News-Reader

**Comment by ildar** [comment]
The OP is duping https://github.com/FredJul/Flym/issues/398 ?

**Comment by Echolon** [comment]
Yes, I will close this as duplicate.
