### ISSUE TITLE
[Feature Request] Sort by oldest

### ISSUE THREAD

**Issue by GMP67** [FredJul/Flym#469]
Could you please port option of showing oldest entries first? It was an essential feature in Flym v1 for me.

**Comment by infinitytec** [comment]
Yes, please.

**Comment by ildar** [comment]
simple search shows this feature was asked many times:
https://github.com/FredJul/Flym/issues/35
https://github.com/FredJul/Flym/issues/41
https://github.com/FredJul/Flym/issues/388
would you please search first?

**Comment by Friptick** [comment]
Pretty please. I have been using SpaRSS abandonware for years now because Flym still does not have this simple feature.

@FredJul: you closed #35 on 27 Jan 2014 saying:
>It's done and will be present in the next version

What am I missing?

**Comment by ildar** [comment]
that was done for Flym v1.
The current v2 is total rewrite making the request actual again.
