### ISSUE TITLE
Full text retrieval fails if <description> tag is missing

### ISSUE THREAD

**Issue by smazh** [FredJul/Flym#479]
Hi FredJul,

Love the app, thanks for all your hard work!

I've noticed that full text retrieval appears to fail for some entries.
Apparently retrieval check seems to be failing if <description> tag is missing in an RSS feed entry, and as the result retrieved content is discarded even if it's valid and has been successfully retrieved.
Example feed having mixed entries with and without description tag: http://static.feed.rbc.ru/rbc/logical/footer/news.rss

**Comment by FredJul** [comment]
Thanks! I never noticed that certainly due to the fact that I don't use feeds without description. This is now fixed and I'll publish a new version of the app today
