### ISSUE TITLE
old articles are reappearing

### ISSUE THREAD

**Issue by agschaid** [FredJul/Flym#487]
For a bit less than a week I have been experiencing reappearing old entries. Entries that I've read 3 or 4 days ago are marked as unread.

Usually it happens to more than one feed at once but appears to restricted to one date. E.g. right now I have an old article from a Haskell blog and one from a cycling blog in my unread-list . . . both from the 3rd of June.

on two occasions I had a bit more than 1000 messages in my list. only 3 of them being genuinely new.

my current version is 2.2.6 installed from F-Droid. It came out a week ago so I guess it introduced that bug.

here is a list of the feeds that happen to suffer from the problem the most:

https://janheine.wordpress.com/feed/

https://planet.haskell.org//rss20.xml

http://scienceblogs.de/astrodicticum-simplex/feed/atom/

but while compiling the list it also dawned on my that these are also among my most active feeds. so it might not be a problem related to the structure of the individual feeds.

let me know if there is any other information I can provide.

**Comment by FredJul** [comment]
hi, I also noticed this issue few days ago. I found the issue and will publish a new version soon.

**Comment by agschaid** [comment]
great. thank you.

in the meantime I reverted to version 2.2.5

**Comment by zmni** [comment]
Sorry for commenting this old issue. I'm on version `2.3.4` and I'm still experiencing the issue, old read feed item keep reappearing.

Here is the list of the feeds:
```
https://github.com/bromite/bromite/releases.atom
https://github.com/macchrome/droidchrome/releases.atom
https://github.com/ram-on/SkyTube/releases.atom
https://www.reddit.com/r/googleplaydeals/new/.rss
```

Can you check this? Might have to wait a while before the old feed item reappears.

Thanks.
