### ISSUE TITLE
[Feature request] Long-press link in article to share/save

### ISSUE THREAD

**Issue by keunes** [FredJul/Flym#488]
In articles there's quite some times a reference to earlier posts or related articles (e.g. with more background information). As I'm using Pocket on my ereader, it'd be nice to be able to save those links quickly to my Pocket account.

A regular tap opens the link, it would be nice if a long-press would allow you to share the link (providing a full list of relevant apps on the phone, or the latest used app as described in #459).

**Comment by FredJul** [comment]
done :) will be available soon

**Comment by keunes** [comment]
Hi @FredJul I don't know if it's a but, or didn't land to my version yet (I have 2.3.1). Long-pressing makes my phone vibrate, but nothing else seems to happen.
