### ISSUE TITLE
Feedly feeds work, but not in Flym

### ISSUE THREAD

**Issue by msummerhayes** [FredJul/Flym#497]
Hello, I used to have GReader Pro and loved it. I have moved to a new Andriod phone and came across your RSS reader. Wow, fab. Great. Except it does not allow me to add two feeds that work in Feedly.

Seth Godin @ https://seths.blog
Julian Summerhayes @ https://juliansummerhayes.com

I have tried to add them and they do not load???? Please advise.

**Comment by wssyncmldm** [comment]
You need to have a proper feed url to add it. For your first blog by
https://seths.blog your RSS feed url is
https://feeds.feedblitz.com/sethsblog

And second blog is wordpress based so RSS url would be
https://juliansummerhayes.com/feed/

**Comment by wssyncmldm** [comment]
Not sure if new flym allows to add feed with url though, just realized that

**Comment by msummerhayes** [comment]
Thanks the 2nd one - Julian - now works. Fab!

However, the Seth Godin one does not..... :( does it need to have a "." at the end?

**Comment by wssyncmldm** [comment]
Updated link

**Comment by msummerhayes** [comment]
Thanks - took the "." off the end and it works fine. many thanks......

**Comment by FredJul** [comment]
As wssyncmldm said, flym is only supporting real feed link and does not try to guess them (I wonder if it is even possible). Hence it's not really a bug, so I close it.
