### ISSUE TITLE
URL for feed

### ISSUE THREAD

**Issue by b16r05** [FredJul/Flym#501]
So, for some websites, URL works but not others. 

1) Bankrate website has a dedicated RSS feed directory page. Nothing seems to work. 

https://www.bankrate.com/finance/rss-directory.aspx

2) Ally bank has an articles page and it is not working. 

https://www.ally.com/do-it-right/

Does any one have any ideas?

**Comment by ildar** [comment]
On Mon, Jun 24, 2019 at 12:48 AM b16r05 <notifications@github.com> wrote:

> So, for some websites, URL works but not others.
>
>    1. Bankrate website has a dedicated RSS feed directory page. Nothing
>    seems to work.
>
> https://www.bankrate.com/finance/rss-directory.aspx
>
all the feeds just don't work in browser.

>
>    1. Ally bank has an articles page and it is not working.
>
> https://www.ally.com/do-it-right/
>
A human being (me) cannot find any feed here. Flym can't do more.

**Comment by wssyncmldm** [comment]
I couldnt find any RSS feed either. Bankrate's RSS feed directory talks
about xml button which doesnt exist in the website to view the feed at all.
And second url, ally.com doesnt have RSS feed at all so that wont work
either

**Comment by b16r05** [comment]
This does it (kind of): https://github.com/yanus171/Handy-News-Reader
