### ISSUE TITLE
settings menu cut at the bottom

### ISSUE THREAD

**Issue by helmat** [FredJul/Flym#527]
Since today's update it's no longer possible to change filters, as the settings menu is cut. See screenshot.

![Screenshot_20190927-054139_Flym](https://user-images.githubusercontent.com/9279616/65740950-ca267d80-e0ea-11e9-9f06-5892fd883638.jpg)

**Comment by FredJul** [comment]
Well, I'm ok to say the UI could be improved a lot, but I'm not sure to understand the problem here: I have the same display and can tap on the options to setup the filters. What is the problem exactly?

**Comment by helmat** [comment]
Well, it just seems the menu is cut just below the "Remove items containing ..." line. I cannot scroll any further down, shouldn't there be a display of the current filters or an explanation in small text like for the other items?

**Comment by FredJul** [comment]
It hasn't been done this way, but yeah, it should be redesigned.

**Comment by fireph** [comment]
This bug seems to no longer exist
