### ISSUE TITLE
[Feature Request] Disable/enable feed sources

### ISSUE THREAD

**Issue by manuelbolzoni** [FredJul/Flym#532]
Hi All,
is it possible to implement deactivation and activation of the synchronization of individual feeds? to be able to temporarily disable a source without having to delete it.
Thanks

**Comment by ildar** [comment]
this can help:
https://github.com/Etuldan/spaRSS/issues/30#issuecomment-115240967

**Comment by manuelbolzoni** [comment]
Duplicate issue, sorry.
