### ISSUE TITLE
[Feature Request] Order of articles

### ISSUE THREAD

**Issue by ArtexJay** [FredJul/Flym#539]
Allow users to view their Feeds from oldest to new and newest to oldest. At the moment its newest to oldest which makes it difficult to catch up or look at some of the older articles.

**Comment by ildar** [comment]
simple search shows this feature was asked many times:
https://github.com/FredJul/Flym/issues/35
https://github.com/FredJul/Flym/issues/41
https://github.com/FredJul/Flym/issues/388
https://github.com/FredJul/Flym/issues/469
would you please search first?

**Comment by ArtexJay** [comment]
K,

**Comment by ArtexJay** [comment]
> simple search shows this feature was asked many times: #35 #388 #469 would you please search first?

K, i guess i searched with the wrong keywords. But thanks for the post with nothing of value.

**Comment by ildar** [comment]
> But thanks for the post with nothing of value
>
Thank you too for filling my mailbox with the same request over and over
again. Did you ever think how much time it takes to read and answer?

**Comment by ArtexJay** [comment]
You can easily delete any mail you get so your complaint is a mute point. Notice how i am not spamming the same complaint over and over like you implied.

Here's a thought if you don't want to reply to a thread then delete it from your mailbox. Easy to do, but you don't need me to tell you that.

Again thanks for yet another post with nothing of value.
