### ISSUE TITLE
Hide container sheet in vertical mode on tablets

### ISSUE THREAD

**Issue by oleastre** [FredJul/Flym#546]
Please revert #543 , or make it configurable somewhere. 
Most of the time, when you are reading rss feeds that provides content, the interesting part is the content, not the list of titles. 
So, what's the reasoning for allocating more than 1/2 of the screen to that list ? 
If the problem is the inconsistency when you rotate your tablet, then it would be more consistent to make it configurable, or add somewhere a button to hide/show the article list.

**Comment by syphyr** [comment]
The previous issue was that available width was only determined on the initial application startup.  So, if Flym was started in landscape mode, then two columns were always shown, even when the device was rotated to portrait.  And if Flym was started in portrait mode, then two columns were never shown, even when the device was rotated to landscape.

**Comment by oleastre** [comment]
I understand the consistency problem that made the layout depend on how Flym was started.
But the current solution to use the horizontal layout even in vertical mode is less than ideal. 
Especially because the article list panel can not be hidden. 
Here is a screenshot of my tablet screen that is 1600x2560px in portrait mode. If I count well, with text margins included, only 714px are use to display the feed content. 
This is a narrow column, not really a nice way to read an article. 
![image](https://user-images.githubusercontent.com/838332/73616821-75ef5500-4618-11ea-9e6e-dc57e6be91e2.png)

![image](https://user-images.githubusercontent.com/838332/73616798-2dd03280-4618-11ea-9e38-bb6dcecf0246.png)

**Comment by syphyr** [comment]
Ideally, one column should always be shown in portrait mode and two columns should always be shown in landscape mode, unless the device is very low resolution and then always show one column in both orientations.

**Comment by syphyr** [comment]
I have tried using orientation qualifiers like "layout-sw840-land/view_main_containers.xml" but it does not work as expected.

**Comment by FredJul** [comment]
I tend to agree, this in indeed not really usable. I reverted #543 until we find another solution.
