### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by de-code** [FredJul/Flym#564]
Hi,

From the screenshot in the README I can see that it should show news item related images. But I can only see feed related letters (e.g. "WO").

The images are in the RSS feed (e.g. [Guardian](https://feeds.theguardian.com/theguardian/world/rss)) as `media:content` elements.

It's a fresh install (2.3.4)

Thank you

**Comment by FredJul** [comment]
You just need to enable the full article mode with a long press on the feed item in the drawer. You'll then see that new articles will have the icon.

It's actually visible only if we see an image in the article itself

**Comment by de-code** [comment]
I can see some images now. There are still a few images missing from the list view, even when an image is displayed within the article view.
