### ISSUE TITLE
Blacklist rarely works

### ISSUE THREAD

**Issue by PrestonMcAfee** [FredJul/Flym#573]
I have a fairly extensive blacklist, separated by commas.  Most of these are authors of the NY times RSS and theweek's RSS.  Usually these fail to be blocked.  I check that they should have been blocked by copying the text from the article and pasting it into the blacklist and it is identical.  Does anyone else use the blacklist feature and is there something I'm doing wrong?

**Comment by FredJul** [comment]
It's just than the filter looks at title and content, not at author list (I didn't even though that people would filter by author).

I believe it's doable. I don't have much time myself but I would accept a Pull Request about that
