### ISSUE TITLE
News links always open in an external app

### ISSUE THREAD

**Issue by PinkDev1** [FredJul/Flym#584]
**APP VERSION:  2.3.4**
**ANDROID: 9.0**

So, when I try to open a news article within flym, it only gives me the option to "open it" on Firefox (my selected browser), Flym, or my podcasts app. 
When I select "open with Flym", a white text box pops up with the news link in it:
![Screenshot_20200503-122704](https://user-images.githubusercontent.com/46269721/80918183-1a795400-8d3a-11ea-91ef-b3d3101248a7.png)
.
I tried going to flym's app settings (system app settings), and see if the "Open by default" was set to something weird, but it just says "No defaults set":
![Screenshot_20200503-123537](https://user-images.githubusercontent.com/46269721/80918327-b60ac480-8d3a-11ea-9704-ae0777a106b7.png)
.
Same thing with Firefox
![Screenshot_20200503-123553](https://user-images.githubusercontent.com/46269721/80918350-da66a100-8d3a-11ea-8208-de05e43c3466.png)

It doesn't open the links IN the app _as it used to_; I don't know why it sudenly changed

**Comment by ildar** [comment]
You mean that tap on link opened a site in the Flym? I never seen that.

**Comment by mitsnosrap** [comment]
Check to see if in the Flym settings "Open in browser" is checked. If it is, that's probably causing this behavior.

**Comment by PinkDev1** [comment]
Yes, looks like that was it!
Looks like I activated it and forgot about it. Thanks
