### ISSUE TITLE
First items not showed from a rss feed

### ISSUE THREAD

**Issue by muziofg** [FredJul/Flym#600]
I'm experiencing a strange behaviour, 

the app don't show me the first two item of this feed http://www.lescienze.it/rss/all/rss2.0.xml 
This happens anytime, why?

**Comment by GeilerHeinz** [comment]
I've noticed a similar behaviour since I installed flym.
After adding https://muenchen.digital/xml/blogfeed.xml yesterday flym was only showing one entry even though the feed is containing many different articles. This morning one additional older entry has been added.

Kind regards

**Comment by GeilerHeinz** [comment]
> I've noticed a similar behaviour since I installed flym.
> After adding https://muenchen.digital/xml/blogfeed.xml yesterday flym was only showing one entry even though the feed is containing many different articles. This morning one additional older entry has been added.
> 
> Kind regards

Curiously I was able to solve my issue by increasing the time span **read** articles are stored to unlimited.

**Comment by muziofg** [comment]
it's a server-side issue, for example different requests with different "accept-encoding" options download contents with different age
