### ISSUE TITLE
Flym doesn't understand this atom feed: https://ef.gy/atom/site

### ISSUE THREAD

**Issue by NANASHI0X74** [FredJul/Flym#633]
Don't get any articles from that feed

**Comment by Oymate** [comment]
This may have something to do
https://ef.gy/feedly-xhtml-content

**Comment by Oymate** [comment]
@NANASHI0X74 Solved: Use this link https://ef.gy/atom/site

**Comment by NANASHI0X74** [comment]
@Oymate that's the same exact link I'm using. I'm still not getting any articles at all from that feed in Flym
Oh, I accidentally wrote feedly in this issue header, didn't I? Let's fix that :sweat_smile: 'Course I meant Flym, wouldn't be very relevant to this repo if I complained about feedly here

**Comment by Oymate** [comment]
@NANASHI0X74 use the second link mine is working fine  :)

**Comment by Oymate** [comment]
Open flym>swipe from left to right>paste link. Click the newly appeared title. Enjoy!

**Comment by NANASHI0X74** [comment]
![ezgif-4-39aea2eed2a5](https://user-images.githubusercontent.com/17546398/89290940-ea539100-d659-11ea-8505-7f11913acb48.gif)
doesn't work for me, I swear 😁

Are we on different versions? I use 2.3.7 according to app details in android settings

**Comment by Oymate** [comment]
It takes 10-ish second to reload, have patience.

**Comment by NANASHI0X74** [comment]
![untitled](https://user-images.githubusercontent.com/17546398/89537664-f0807380-d7f9-11ea-9903-b9616a744456.gif)

I tried building the current master branch (Version 2.40) and let it run on android virtual device. Doesn't work there either

**Comment by ildar** [comment]
Would you look at adb logcat? It shows tons of useful info.

**Comment by NANASHI0X74** [comment]
I did originally, but didn't see anything useful. I tried again today and spotted these logs:

```
2020-08-07 10:17:24.162 9203-9231/net.frju.flym W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2020-08-07 10:17:24.162 9203-9231/net.frju.flym W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2020-08-07 10:17:24.162 9203-9231/net.frju.flym W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I guess that might  be the reason why.

**Comment by NANASHI0X74** [comment]
Ok, I've solved my problem. Aparently when initally getting feeds, if the entries in the feed are older than 'time that read entries will be kept' they won't appear in flym. cf. #571
