### ISSUE TITLE
Offer: Label all open issues

### ISSUE THREAD

**Issue by Echolon** [FredJul/Flym#640]
Hi @FredJul, 

if that would help you and you are interested, I can offer to work through the repository and label all open issues.

I did and do that for Jitsi, Monal, Yaxim and Pix-Art aswell. Just see my profile.

Thanks for the reader using it every day.

**Comment by FredJul** [comment]
Hi,

Clearly that's something which would be helpful! I still maintain Flym but I don't have time and motivation anymore to try to fix issues and even sort/deduplicate them, so I encourage anyone from the community to take over it, and having a clear view of the issues will certainly help! So thank a lot for your proposal.

I just gave you the "collaborator" right, just in case it is needed to create labels.

**Comment by Echolon** [comment]
Ouh thats sad, I actually really like the app. Have you tried to advertise that encouragement?

**Comment by FredJul** [comment]
Well, most of modifications are community-driven since a year, so it does not mean the app is dead and I'm quite happy with that, even if I would like even more people involved.
The main page description mentions that I encourage it.

**Comment by Echolon** [comment]
Okay, I suggest to create a informational update within the app as well. Maybe users are not aware but would be interested.

**Comment by FredJul** [comment]
That's actually a good idea, I will do that :)
