### ISSUE TITLE
Black navigation bar in Android light mode.

### ISSUE THREAD

**Issue by justwholegrain** [FredJul/Flym#674]
After the last update (2.5.1) the navigation bar turned black when viewed entries list. It is still correct (white/light) if viewed settings or reading article. When I 'search' in entries list is white when it displays the keyboard or black when keayboard is hidden :/

The issue does not apply to the new feature 'Hide navigation when scrolling', but it probably little messed up the display of the nav bar. @fireph :)

I'm using a light android mode;
without gestures;
App is also light theme;
Android 9;
Xiaomi, MIUI 11;

**Comment by fireph** [comment]
Ah I know why this happens, I can make a PR to fix this :)
