### ISSUE TITLE
How to add my Blog to the search results?

### ISSUE THREAD

**Issue by SCRUMschau** [FredJul/Flym#698]
I want to add my own blog ( https://scrumschau.wordpress.com ) to the rss reader.

When I search for "scrumschau" I cannot find my blog.

How can I add my blog to the search result list?

![grafik](https://user-images.githubusercontent.com/43698661/95364634-5dcf8400-08d1-11eb-9c50-9030a037e8b3.png)

**Comment by farazmah** [comment]
I am also trying to add a blog that is not found in the search.  How can I add a custom feed url?

**Comment by FredJul** [comment]
I use the Feedly API for that, so you should ask them directly, I cannot do much myself

**Comment by farazmah** [comment]
Thanks for the prompt reply
Adding custom feeds was one of the features that attracted me to this app in the first place.  The old version on google play still has this functionality.

**Comment by FredJul** [comment]
Oh sorry I misunderstood your point... You can still add a custom RSS feed url in flym, just copy the url into the search field. If it's a correct feed, you'll be able to add it.

Isn't it working?

**Comment by farazmah** [comment]
I must have typed the url incorrectly or something.  I am trying it again and seems to be ok. 
Thanks
