### ISSUE TITLE
WebView privacy

### ISSUE THREAD

**Issue by duggalsu** [FredJul/Flym#710]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest - 
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```

**Comment by nikhilCad** [comment]
This app has webview?? Where??

**Comment by duggalsu** [comment]
I saw it here 
https://github.com/FredJul/Flym/blob/master/app/src/main/java/net/frju/flym/ui/entrydetails/EntryDetailsView.kt

**Comment by amkcpu** [comment]
I just opened a pull request to address that.
For reference: Flym uses WebView to display articles (that's what the `EntryDetailsView` does). That's because the articles are HTML that is parsed and somewhat adjusted by Flym.

**Comment by FredJul** [comment]
Thanks to both of you for the proposal and the PR! I just merged it.
