### ISSUE TITLE
Feed works correctly in other apps, but Flyn shows no entries

### ISSUE THREAD

**Issue by TheDeviantCrafter** [FredJul/Flym#729]
This link fails to load any entries in Flym, even when set to display all: https://forums.warframe.com/forum/2-pc-announcements.xml/

This link works fine: https://forums.warframe.com/forum/3-pc-update-notes.xml/

Both links look the same to my untrained eye, and display correctly in [this RSS preview tool](https://www.coderedcorp.com/tools/rss-preview/)

The links match the ones above in the Edit Feed menu that appears when long pressing the feed.

The second link is only updated every week or two, and hasn't updated since I started troubleshooting this issue. That may be related.

**Comment by infinitytec** [comment]
I'm noticing this as well with https://www.dailywire.com/rss.xml

**Comment by TheDeviantCrafter** [comment]
The feed started updating after a new post was made.
