### ISSUE TITLE
Feeds from reddit have no thumbnail image

### ISSUE THREAD

**Issue by Donkey-Doug** [FredJul/Flym#743]
On most other news readers, feeds from reddit show an image. Flym shows nothing.

Example of a reddit RSS feed: https://www.reddit.com/r/Android/.rss

**Comment by yawks** [comment]
Have you tried with the last build (from december the 16th)?
I tried your RSS feed and the thumbnails are ok:
![image](https://user-images.githubusercontent.com/4396128/107259593-785f6880-6a3d-11eb-8ba5-8430a2a60f43.png)

**Comment by Donkey-Doug** [comment]
It does indeed work. I do not know why it did not earlier.
