### ISSUE TITLE
Feeds disappear

### ISSUE THREAD

**Issue by dalb8** [FredJul/Flym#87]
I noticed that at least a couple of feeds have disappeared. When I try to add them again it says the 'feed exists already' . One of them is https://tails.boum.org/news/index.en.atom; it exists in the edit feed list but isnt visible in the drawer. It returned after a full sync of all feeds, which I rarely do.  I'm using 1.5.0 built from source on CM10.1.

**Comment by FredJul** [comment]
Correct me if I'm wrong but this issue cannot be reproduced anymore.
